global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gradio_app'
    static_configs:
      - targets: ['xkcd_finder_app:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['xkcd_finder_app:9100']